### ISSUE TITLE
Stopped working on Ubuntu 13.10 Virtual Box

### ISSUE THREAD

**Issue by dharkness** [sindresorhus/load-grunt-tasks#28]
One of our developers started getting this error this morning:

```
>> Error: Cannot find module 'load-grunt-tasks'
```

We can see the package in `node_modules`. He didn't do any updates Friday or today, and we haven't changed the list of Grunt tasks we use in months. He did a complete uninstall of node.js, npm, and all node modules, and reinstalled using the node v.0.10.29 tarball, `npm install && npm update`, but the problem persists.

Replacing `load-grunt-tasks` with the original calls to `grunt.loadNpmTasks` works as expected, but that's obviously suboptimal because `load-grunt-tasks` is too awesome not to use. :(

```
node: v0.10.29
npm: 1.4.14
```

I'm sure this report doesn't contain enough information to help you diagnose the issue, so please advise what else I can supply. Thanks!
